services:
  ml-service:
    build: .
    #image: potapovjakov/dendroscan-ml:dev-torch
    env_file:
      - .env
    ports:
      - "8080:8000"
    restart: unless-stopped
    volumes:
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
