# -------------------- Фильтры --------------------
filters = {
    "plants": [
        "a birch",
        "an oak",
        "a maple",
        "a pine",
        "a spruce",
        "a cedar",
        "Norway maple",
        "larch",
        "thuja",
        "rowan",
        "shrub pine",
        "juniper",
        "potentilla fruticosa (shrub cinquefoil)",
        "chestnut",
        "willow",
        "ash-leaved maple (box elder)",
        "aspen",
        "linden",
        "ash tree",
        "elm",
        "mock-orange",
        "common lilac",
        "caragana arborescens (Siberian pea tree)",
        "physocarpus opulifolius (ninebark)",
        "spiraea",
        "cotoneaster",
        "cornus alba (Siberian dogwood)",
        "hazel",
        "hawthorn",
        "dog rose",
        "rugosa rose"
    ],

    "defects": [
        "trunk rot on a tree",
        "cracks in the tree trunk",
        "tree trunk damage",
        "a hollow in a tree",
        "severe root collar rot",
        "severe trunk rot",
        "extensive drywood",
        "hollow",
        "mechanical damage",
        "bark peeling",
        "fruiting body rot",
        "dead standing tree",
        "damaged by pests",
        "partial root system failure",
        "severe canker",
        "stump",
        "drywood defect",
        "deep longitudinal crack",
        "complete root system failure",
        "dry branches more than 75%",
        "dry branches 50% to 75%",
        "dry branches 25% to 50%",
        "dry branches up to 25%",
        "dieback of the crown",
        "a slightly leaning tree",
        "a significantly leaning tree",
        "crack"
    ]
}

# -------------------- Переводы --------------------
translations = {
    # species
    "a birch": "Берёза",
    "an oak": "Дуб",
    "a maple": "Клён",
    "a pine": "Сосна",
    "a spruce": "Ель",
    "a cedar": "Кедр",
    "Norway maple": "Клён остролистный",
    "larch": "Лиственница",
    "thuja": "Туя",
    "rowan": "Рябина",
    "shrub pine": "Сосна (кустарниковая форма)",
    "juniper": "Можжевельник",
    "potentilla fruticosa (shrub cinquefoil)": "Лапчатка кустарниковая (курильский чай)",
    "chestnut": "Каштан",
    "willow": "Ива",
    "ash-leaved maple (box elder)": "Клён ясенелистный",
    "aspen": "Осина",
    "linden": "Липа",
    "ash tree": "Ясень",
    "elm": "Вяз",
    "mock-orange": "Чубушник",
    "common lilac": "Сирень обыкновенная",
    "caragana arborescens (Siberian pea tree)": "Карагана древовидная",
    "physocarpus opulifolius (ninebark)": "Пузыреплодник калинолистный",
    "spiraea": "Спирея",
    "cotoneaster": "Кизильник",
    "cornus alba (Siberian dogwood)": "Дёрен белый",
    "hazel": "Лещина",
    "hawthorn": "Боярышник",
    "dog rose": "Шиповник собачий",
    "rugosa rose": "Роза морщинистая",

    # problems
    "trunk rot on a tree": "Гниль ствола",
    "cracks in the tree trunk": "Трещины на стволе",
    "tree trunk damage": "Повреждение ствола",
    "a hollow in a tree": "Дупло",
    "severe root collar rot": "Комлевая гниль (сильная степень)",
    "severe trunk rot": "Стволовая гниль (сильная степень)",
    "extensive drywood": "Обширная сухобочина",
    "hollow": "Дупло",
    "mechanical damage": "Механические повреждения",
    "bark peeling": "Отслоение коры",
    "fruiting body rot": "Гниль плодовых тел",
    "dead standing tree": "Сухостой",
    "damaged by pests": "Повреждено вредителями",
    "partial root system failure": "Частичный вывал корневой системы",
    "severe canker": "Рак (сильная степень)",
    "stump": "Пень",
    "drywood defect": "Сухобочина",
    "deep longitudinal crack": "Глубокая продольная трещина",
    "complete root system failure": "Вывал корневой системы",
    "dry branches more than 75%": "Сухие ветви более 75%",
    "dry branches 50% to 75%": "Сухие ветви от 50% до 75%",
    "dry branches 25% to 50%": "Сухие ветви от 25% до 50%",
    "dry branches up to 25%": "Сухие ветви до 25%",
    "dieback of the crown": "Суховершинность",
    "crack": "Трещина",

    # leaning
    "a straight tree": "Прямое дерево",
    "a slightly leaning tree": "Слегка наклонённое дерево",
    "a significantly leaning tree": "Сильно наклонённое дерево"
}

latin_names = {
    "Norway maple": "Acer platanoides",
    "larch": "Larix",
    "thuja": "Thuja",
    "rowan": "Sorbus",
    "birch": "Betula",
    "chestnut": "Castanea",
    "willow": "Salix",
    "ash-leaved maple (box elder)": "Acer negundo",
    "aspen": "Populus tremula",
    "linden": "Tilia",
    "ash tree": "Fraxinus",
    "oak": "Quercus",
    "spruce": "Picea",
    "pine": "Pinus",
    "elm": "Ulmus",
    "shrub pine": "Pinus sylvestris f. fruticosa",
    "juniper": "Juniperus",
    "potentilla fruticosa (shrub cinquefoil)": "Pentaphylloides fruticosa",
    "mock-orange": "Philadelphus",
    "common lilac": "Syringa vulgaris",
    "caragana arborescens (Siberian pea tree)": "Caragana arborescens",
    "physocarpus opulifolius (ninebark)": "Physocarpus opulifolius",
    "spiraea": "Spiraea",
    "cotoneaster": "Cotoneaster",
    "cornus alba (Siberian dogwood)": "Cornus alba",
    "hazel": "Corylus",
    "hawthorn": "Crataegus",
    "dog rose": "Rosa canina",
    "rugosa rose": "Rosa rugosa",
}