translation_dict = {
    "norway maple (acer platanoides) tree": ("Клён остролистный", "Acer platanoides"),
    "larch (larix) tree": ("Лиственница", "Larix"),
    "thuja (thuja) tree": ("Туя", "Thuja"),
    "rowan (sorbus) tree": ("Рябина", "Sorbus"),
    "birch (betula) tree": ("Берёза", "Betula"),
    "chestnut (castanea) tree": ("Каштан", "Castanea"),
    "willow (salix) tree": ("Ива", "Salix"),
    "boxelder maple (acer negundo) tree": ("Клён ясенелистный", "Acer negundo"),
    "aspen (populus tremula) tree": ("Осина", "Populus tremula"),
    "linden (tilia) tree": ("Липа", "Tilia"),
    "ash (fraxinus) tree": ("Ясень", "Fraxinus"),
    "oak (quercus) tree": ("Дуб", "Quercus"),
    "spruce (picea) tree": ("Ель", "Picea"),
    "pine (pinus) tree": ("Сосна", "Pinus"),
    "elm (ulmus) tree": ("Вяз", "Ulmus"),

    "dwarf scots pine (pinus sylvestris f. fruticosa) bush": ("Карликовая сосна", "Pinus sylvestris f. fruticosa"),
    "juniper (juniperus) bush": ("Можжевельник", "Juniperus"),
    "shrubby cinquefoil (pentaphylloides fruticosa) bush": ("Пятилистная лапчатка", "Pentaphylloides fruticosa"),
    "mock-orange (philadelphus) bush": ("Филадельфус", "Philadelphus"),
    "common lilac (syringa vulgaris) bush": ("Сирень обыкновенная", "Syringa vulgaris"),
    "siberian peashrub (caragana arborescens) bush": ("Карагана древовидная", "Caragana arborescens"),
    "ninebark (physocarpus opulifolius) bush": ("Пузыреплодник калинолистный", "Physocarpus opulifolius"),
    "spirea (spiraea) bush": ("Спирея", "Spiraea"),
    "cotoneaster (cotoneaster) bush": ("Кизильник", "Cotoneaster"),
    "siberian dogwood (cornus alba) bush": ("Дерен белый", "Cornus alba"),
    "hazelnut (corylus) bush": ("Лещина", "Corylus"),
    "hawthorn (crataegus) bush": ("Боярышник", "Crataegus"),
    "dog rose (rosa canina) bush": ("Шиповник", "Rosa canina"),
    "rugosa rose (rosa rugosa) bush": ("Роза морщинистая", "Rosa rugosa"),
}